# Generated by Django 2.2 on 2019-04-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_libro_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='generos',
            field=models.ManyToManyField(to='app1.Genero'),
        ),
    ]
